Конструктор секций: Добавлен плагин
Bim4Everyone/BIMExtensions pull request #22
Opened 2024-05-07 07:11 UTC by vlastroG

Инструмент для быстрого создания типовых секций, состоящих из фиксированного набора типовых этажей. Каждый типовой этаж - группа или несколько групп.

![image](https://github.com/Bim4Everyone/RevitPlugins/assets/87359016/751bf959-88a9-4304-a3da-fb0eefd04bda)

**Описание работы с плагином:**
Пользователь создает файл типовой секции и размещает экземпляры типовых этажей на соответствующих этажах. Пользователь размещает по 1 экземпляру для каждого типового этажа. При необходимости внутри внутри любой другой группы типового этажа пользователь может добавить вложенную группу, например для санузлов.
После того, как файл подготовлен, пользователь запускат плагин. Плагин находит все размещенные экземпляры родительских групп и выводит их пользователю в главном окне. В этом окне только родительские группы, которые не являются вложенными группами в другие группы. Далее в этом окне для каждого экземпляра группы пользователь определяет действие. Возможные действия над экземплярами групп это:
 - оставить без изменения и никак не обрабатывать
 - удалить экземпляр группы
 - скопировать экземпляр группы на заданные этажи. Если группу не нужно копировать на текущий этаж, с этого текущего этажа группа удаляется. Если группу нужно копировать на текущий этаж, то группа на этом этаже остается как есть.

По умолчанию для каждой группы в плагине предусмотрено действие оставить без изменения и никак не обрабатывать.
После задания действий над экземплярами группами пользователь выбирает директорию в файловой системе ПК, на котором запущен плагин, куда надо будет сохранить файл с примененными действиями. Пользователь нажимает "ОК", в файле применяются действия над экземплярами групп, файл сохраняется со сжатием как файл хранилище по заданному пути, выполняется синхронизация со сжатием с освобождением всех рабочих наборов. Если файл изначально не был файлом для совместоной работы, то он только сохраняется со сжатием по заданному пути.

**ВАЖНО** запускать плагин, когда в активном документе открыт только 1 вид и этот активный вид не содержит геометрии модели. Идеальный вариант - запускать плагин на начальном листе. При запуске плагина на других видах Revit может зависнуть во время отрисовки графики после применения большого количества изменений.

2024-06-07 13:42 UTC, dosymep requested changes

2024-06-07 13:42 UTC, dosymep commented on BIM.tab/ОПП.panel/Конструктор секций.invokebutton/bundle.yaml
> +    Конструирует типовые секции из экземпляров групп типовых этажей
Добавь более расширенное описание, как запускать, с какими документами, какой вид требуется, возможно мини инструкцию

2024-06-10 08:38 UTC, vlastroG commented on BIM.tab/ОПП.panel/Конструктор секций.invokebutton/bundle.yaml
> +    Конструирует типовые секции из экземпляров групп типовых этажей
Обновил описание

2024-06-10 08:39 UTC, dosymep approved these changes
Красота!

2024-06-10 08:39 UTC, merged