Расставить на элемент: Создан плагин
Bim4Everyone/BIMExtensions pull request #59
Opened 2024-10-21 06:59 UTC by Redomine

Плагин, расширяющий функционал выдачи задания на отверстия. В отличии от основного модуля, не требует для себя основы, блок задания ставится в точке на линейном элементе(воздуховод, труба, короб, лоток), на которую кликнул пользователь. 

Работает только с горизонтальными коммуникациями, вертикальные отсеиваются. (Исключая те которые идут под небольшим углом, но их уже тяжело распознать)

2024-10-22 07:00 UTC, vlastroG requested changes
Реши ситуацию с параметрами для отметок, сейчас существующий плагин не совместим с ними

2024-10-22 12:24 UTC, Redomine commented on BIM.tab/Отверстия.panel/Отверстия ВИС.pulldown/Расставить на элемент.pushbutton/script.py
> +shared_level_offset_name = "ADSK_Отверстие_ОтметкаЭтажа"
Очистил семейства от формул, добавил обработку всех параметров в скрипт.

Проблема следующая: 
У нас имеется две группы параметров ADSK, отвечающих за отметку.
Параметры с пробелами - (Отметка от нуля и тд) - это длина. 
Параметры без пробелов - (ОтметкаОтНуля) - денежная единица.

Все наши шаблоны и выноски строятся на втором. Но это ложный параметр, который не существует в нормальном ADSK.

Тем не менее - выпилить его из употребления задача почти нерешаемая, оно просто везде. Поэтому просто обрабатываем обе группы.

2024-10-22 12:40 UTC, vlastroG approved these changes

2024-10-31 14:01 UTC, dosymep approved these changes

2024-10-31 14:02 UTC, merged