Проверка на зеркальность: Создан плагин
Bim4Everyone/BIMExtensions pull request #75
Opened 2024-11-18 14:26 UTC by KGubin

Плагин обрабатывает выбранные элементы или категории элементов на предмет "отзеркаленности" по внутреннему параметру и задаёт значение "0" или "1" параметру "ФОП_Зеркальность" в зависимости от статуса зеркальности и выполняет следующий функции:
- Добавляет признака "ФОП_зеркальность" в Revit
- Заполняет признака "ФОП_зеркальность" у выбранных элементов
- Выделяет элементы с признаком "ФОП_зеркальность" равное 1, на временном виде и подсвечивает их красным.
- Выделяет элементов с признаком "ФОП_зеркальность" равное  1, на активном виде.

2024-11-20 11:43 UTC, vlastroG requested changes

2024-11-20 11:43 UTC, vlastroG commented on BIM.tab/Проверки.panel/Проверка на зеркальность.invokebutton/bundle.yaml
> +
Скорректируй ссылку, сейчас она ведёт на панель "Отверстия"

2024-11-20 12:08 UTC, KGubin commented on BIM.tab/Проверки.panel/Проверка на зеркальность.invokebutton/bundle.yaml
> +
Исправил

2024-11-20 13:16 UTC, vlastroG submitted a review, later dismissed

2024-11-25 10:23 UTC, dosymep requested changes

2024-11-25 10:23 UTC, dosymep commented on BIM.tab/Проверки.panel/Проверка на зеркальность.invokebutton/bundle.yaml
> +context:
контекст тут не рекомендую использовать, если надо ограничить доступ, лучше дать пользователю информационное сообщение, после запуска плагина

2024-11-27 10:47 UTC, merged